export const CORE_GENRE_STRING = "Pop,Hip-Hop,Trap,R&B,Neo-Soul,Country,Folk,Rock,Alt Rock,EDM,House,Metal,Punk,Emo,Jazz,Reggae,Gospel,Classical Crossover,Ska,Soul";
export const CORE_GENRES = CORE_GENRE_STRING.split(",");

export const FLAVOR_STRING = "Indie,Synthwave,Shoegaze,Dream Pop,Tech House,Drum & Bass,Darkwave,Hyperpop,City Pop,Cyberpunk,Space Rock,Post-Rock,Progressive,Psychedelic,Acoustic,Lo-Fi,Orchestral,Cinematic,Afrobeat,Amapiano,Baile Funk,Cumbia,Motown,Outlaw,G-Funk,Industrial,Sludge,Doom,Goth,Math,Pirate,Viking,Glitch,Future Bass,Tropical,Vaporwave,Chiptune,Baroque,Acid,Neo-Psychedelia,New Wave,No Wave,Swamp,Yacht,Ambient,Dark Ambient,Drone,Microhouse,Minimal,Neoclassical,Folktronica,Electro Swing";
export const FLAVORS = FLAVOR_STRING.split(",");

export const TOPIC_STRING = "Leaving your hometown without saying goodbye|A love that never commits but won't let go|Rebuilding your life after a public failure|A friendship fading quietly over text messages|Wanting revenge but choosing peace instead|Feeling out of place in your own childhood bedroom|Missing someone you know is terrible for you|Starting over in a city where nobody knows your name|Being addicted to the memory of how things were|Chasing a dream that’s slowly turning you bitter|Talking to your younger self in the mirror|A night drive with no destination just to avoid going home|Learning to forgive yourself for the things you broke|Falling for the wrong person at exactly the right time|A promise you made at 16 that you couldn't keep|Growing apart gracefully instead of fighting|Realizing your parents were just kids figuring it out too|The exact moment you fall out of love|Pretending you don't care when they walk into the room|Deleting their number but having it memorized|Finding their old t-shirt in your drawer and deciding to burn it|Realizing your hometown feels like a stranger|A toxic friendship you can't let go of|The terrifying freedom of finally quitting a job you hate|Watching someone else live the life you planned together|Feeling like an imposter in your own success|The paranoia of things going too well|Reconnecting with an ex only to remember why you left|Dressing up with nowhere to go just to feel alive|The guilt of moving on faster than you thought you would|A crush that's entirely built on eye contact and no words|Realizing the 'one that got away' was actually a bullet dodged|The comfort of being alone in a crowded diner at 2 AM|Choosing your ambition over your relationship|The awkwardness of bumping into someone you used to tell everything to|Holding onto a grudge because it's the only connection left|Falling in love with your best friend but being too scared to say it|The specific grief of a pet dying|Watching a parent get older and realizing time is running out|Feeling homesick for a place you've never been|The chaotic energy of a night out that goes completely off the rails|Regretting the text the second it says 'Read'|The intoxicating rush of a secret romance|Trying to fix someone who doesn't want to be fixed|The exhaustion of always being the 'strong' friend|Realizing you've become exactly like your mother|The bittersweet feeling of boxing up an apartment|A summer romance that you knew had an expiration date|The betrayal of your body failing you|Discovering a secret that changes your entire past|The slow realization that you are the villain in someone else's story|Apologizing when you know you aren't wrong just to keep the peace|The specific loneliness of New Year's Eve|Finding a love letter meant for someone else|The terrifying realization that you're an adult now|Staying in a relationship just because it's comfortable|The resentment of carrying the emotional load|A sudden epiphany on a boring Tuesday commute|The panic of realizing you forgot how to be single|Watching your friends hit milestones while you feel stuck|The strange intimacy of sharing a silence with a stranger|The guilt of surviving something others didn't|Falling for someone strictly because they pay attention to you|The relief of finally admitting you were wrong|The desperate attempt to recreate a perfect memory|Realizing the person you idolized is incredibly flawed|The exhaustion of keeping up a perfect online persona|The specific joy of canceling plans to stay in bed|A fleeting connection on public transit that you'll never forget|The quiet devastation of being uninvited|The awkward transition from lovers back to strangers|The fierce protectiveness over a younger sibling|The slow creep of apathy in a long-term relationship|The sudden urge to shave your head and change your name|The nostalgia for an era you didn't even live through|The brutal honesty of a drunken confession|The strange peace of hitting rock bottom|The manic energy of a caffeine-fueled all-nighter|The creeping realization that your dream job is a nightmare|The specific pain of being misunderstood by someone who claims to know you|The intoxicating power of finally setting a boundary|The lingering ghost of an unsaid goodbye|The terrifying vulnerability of asking for help|The strange camaraderie of the smoking section|The sudden, overwhelming appreciation for a simple sunny day|The dread of a Sunday evening|The hollow victory of winning an argument you shouldn't have started|The specific magic of the first snow of the year|The crushing weight of unfulfilled potential|The slow process of falling back in love with your partner|The disorientation of waking up in a hotel room and forgetting where you are|The specific brand of crazy that comes from sleep deprivation|The fierce, unspoken bond between outcasts|The sudden clarity that comes after a good cry|The bittersweet taste of a final paycheck|The eerie quiet of an empty school building|The specific anxiety of waiting for test results|The profound realization that nobody actually knows what they're doing|The quiet act of rebellion in doing absolutely nothing";
export const TOPICS = TOPIC_STRING.split("|");

export const IMAGERY_STRING = "Neon flickering on a wet windshield|The smell of stale coffee and regret|Static on an old CRT television|Fading summer light cutting through dusty blinds|Dusty photos shoved in the back of a junk drawer|Cold air rushing into an empty, dark room|A cigarette burning down unnoticed in an ashtray|Motel curtains glowing orange at sunrise|Ocean salt drying tight on sunburned skin|Train stations echoing with missed calls and delays|Streetlights buzzing and flickering on a quiet suburban road|Snow falling silently on untouched pavement|A violently cracked phone screen glowing in the dark|Warm, yellow kitchen lamplight at 3 AM|Shattered glass glittering like diamonds on the asphalt|The heavy, oppressive humidity before a thunderstorm|A faded Polaroid curling at the edges|The distinct smell of old books and dried roses|A lone pair of sneakers dangling from a power line|The blinding glare of oncoming headlights|Mascara running down in jagged black rivers|The metallic taste of a split lip|A moth desperately battering against a porch light|The suffocating smell of cheap cologne and sweat|A chipped coffee mug leaving brown rings on a wooden table|The rhythmic, hypnotic thump of a distant bassline|A handful of melted ice cream dripping down a wrist|The blinding fluorescence of a 24-hour convenience store|A forgotten umbrella turning inside out in the wind|The sharp, clean scent of pine needles and frost|A crumpled handwritten note dissolving in a puddle|The eerie glow of a dashboard tracking a dark highway|A half-empty bottle of whiskey catching the afternoon sun|The chaotic tangle of charger cords on a nightstand|A lone red balloon trapped in a bare tree|The deafening roar of silence after a door slams|A perfectly applied swipe of red lipstick on a coffee cup|The rough texture of a brick wall against a scraped knuckle|A sky bruised with purple and bruised-yellow clouds|The jarring ring of an old rotary phone|A flickering fluorescent tube in a dingy restroom|The soft, rhythmic ticking of a grandfather clock in an empty house|A wilted bouquet of gas-station flowers|The stark contrast of dark blood on white snow|A dizzying kaleidoscope of stage lights cutting through fog|The specific hollow sound of a pebble hitting a window|A ripped concert ticket stub slowly fading in a wallet|The stinging slap of freezing rain on bare cheeks|A pile of unread mail gathering dust on the counter|The electric hum of a vending machine in a deserted hallway|The warm, suffocating smell of a crowded subway car|A single tear cutting a clean path through dirty cheeks|The blinding reflection of the sun off the ocean|A forgotten bicycle rusting in tall grass|The sharp crack of a pool ball breaking the silence|A constellation of freckles across a sunburnt nose|The heavy drag of a velvet curtain falling closed|A flickering candle casting long, monstrous shadows|The specific smell of chlorine and sunscreen on a summer afternoon|A tangled mess of cassette tape spilled on the floor|The stark white lines of a freshly painted crosswalk|A handful of loose change glinting on a bar top|The hollow, echoing thud of a dropped heartbeat|A swirling galaxy of dust motes in a shaft of sunlight|The sticky sweetness of spilled soda on a movie theater floor|The jagged edge of a torn photograph|A lone seagull crying over an empty winter beach|The blinding flash of a paparazzi camera|The soft, muffled crunch of footsteps in fresh snow|A discarded wedding ring sitting on a bathroom sink|The chaotic smear of city lights from a moving train|The specific scent of a freshly struck match|A worn-out leather jacket smelling of smoke and nostalgia|The dizzying blur of a spinning record|A single, perfect dewdrop trembling on a blade of grass|The harsh, abrasive scrape of a chair on a concrete floor|A forgotten doll sitting perfectly still on a dusty shelf|The blinding white of a blank page|The chaotic tangle of bedsheets after a restless night|A single, glowing ember in a dying fire|The specific sound of a key turning in a lock|A cracked rearview mirror showing a distorted past|The overwhelming smell of hospital antiseptic|A single, vibrant red leaf clinging to a bare branch|The dizzying spiral of a spiral staircase|A forgotten coffee cup balancing precariously on a railing|The sharp, sudden bite of winter wind|A swirling vortex of autumn leaves caught in an updraft|The blinding glare of a blank billboard|A lone pair of headlights cutting through thick fog|The specific sound of rain drumming on a tin roof|A forgotten scarf tied to a park bench|The harsh, mechanical buzz of an alarm clock|A single, perfect snowflake melting on an eyelash|The dizzying array of colors in a spilled oil slick|A forgotten love letter tucked into an old paperback|The sharp, distinct smell of freshly cut grass|A single, perfect tear dropping onto a keyboard|The chaotic jumble of thoughts in a crowded mind";
export const IMAGERY = IMAGERY_STRING.split("|");

export const STRUCTURES = [
  { name: "Modern Pop Arc", steps: [["Verse 1", "Scene setting", "Concrete details, one strong image per line."], ["Pre-Chorus", "Tension climb", "Shorten lines, raise urgency, hint the thesis."], ["Chorus", "Thesis + hook", "One clear statement, repeatable phrasing."], ["Verse 2", "Contrast / escalation", "Add a twist, reveal imbalance or regret."], ["Pre-Chorus", "Higher stakes", "Same shape, sharper confession."], ["Chorus", "Bigger payoff", "Add one new line at the end for lift."], ["Bridge", "Perspective flip", "Say one plain truth with no metaphor."], ["Final Chorus", "Expanded hook", "Stack harmonies, extend the last phrase."]] },
  { name: "Alt / Indie Narrative", steps: [["Verse 1", "Place + moment", "Anchor in time/location. Let details do the work."], ["Chorus", "Emotional summary", "Not too literal—one memorable phrase."], ["Verse 2", "Memory replay", "Show the same event from a new angle."], ["Chorus", "Reframe", "Same hook, changed meaning with one new word."], ["Bridge", "Confession", "Drop the ‘cool’—be embarrassingly honest once."], ["Final Chorus", "Resolution", "Either acceptance or refusal. No in-between."]] },
  { name: "Rap / R&B Switch-Up", steps: [["Intro", "Tone-set", "One-liner that defines the vibe."], ["Verse", "Detail + flex", "Specifics, clever images, internal rhyme pockets."], ["Hook", "Sticky mantra", "Short, repeatable, emotionally loaded."], ["Verse 2", "Escalate / reveal", "Add vulnerability or a contradiction."], ["Bridge", "Melodic lift", "Stretch vowels, simplify language, let it breathe."], ["Final Hook", "Harder", "Double the cadence or add ad-libs."]] },
  { name: "The Classic AABA (Jazz/Showtune)", steps: [["Section A1", "Introduce theme", "Establish the core melody and lyrical premise quickly."], ["Section A2", "Reinforce theme", "Same melody, advance the plot or change the setting."], ["Section B (Bridge)", "The Turn", "Completely different chords/melody. Shift perspective or time."], ["Section A3", "Resolution", "Return to the familiar melody, concluding the emotional thought."]] },
  { name: "EDM Build & Drop", steps: [["Intro", "Atmosphere", "Sparse instrumentation, whispered or highly affected vocal."], ["Verse", "Building energy", "Rhythm speeds up, lyrics become more frantic or urgent."], ["Pre-Drop Build", "Maximum Tension", "Rising pitch, repeating a single powerful phrase over and over."], ["The Drop", "Release", "Minimal to no vocals. Let the production carry the emotion."], ["Outro", "Fade out", "Return to the sparse intro atmosphere, echoing the final word."]] },
  { name: "Folk Ballad Storyteller", steps: [["Verse 1", "The Setup", "Introduce characters and the core conflict."], ["Chorus", "The Moral", "A timeless, folksy observation about the situation."], ["Verse 2", "The Complication", "Things go wrong. Add a tragic or ironic twist."], ["Chorus", "The Moral Returns", "The same words now carry heavier meaning."], ["Verse 3", "The Aftermath", "Years later, or the final consequence."], ["Outro", "Drifting off", "A single acoustic instrument fading into the wind."]] },
  { name: "Punk / Hardcore Blitz", steps: [["Intro", "Count off", "Fast, aggressive start. No time to think."], ["Verse 1", "The Grievance", "Shouted vocals, fast tempo, angry observation."], ["Chorus", "The Anthem", "Chanted group vocals, rebellious punchline."], ["Verse 2", "The Escalation", "Shorter than verse 1, double the intensity."], ["Breakdown", "Half-time crush", "Tempo drops by half, extremely heavy, guttural vocal delivery."], ["Outro", "Abrupt stop", "Feedback ring-out. Leave them wanting more."]] },
  { name: "K-Pop Rollercoaster", steps: [["Intro", "Catchy Signature", "A distinct sound or spoken phrase to brand the song."], ["Verse 1", "Smooth & Sweet", "Clean vocals, setting a confident mood."], ["Rap Verse", "Attitude Shift", "Sudden tempo/beat change, fast rhythmic delivery."], ["Pre-Chorus", "Vocal Flex", "Soaring high notes building immense anticipation."], ["Chorus", "The Ultimate Hook", "Explosive energy, massive synth lines, repetitive sticky phrase."], ["Post-Chorus", "Dance Break", "Heavy beat, single chanted word or non-lexical vocables."], ["Bridge", "Emotional drop", "Stripped back, vulnerable, leading to a massive high note."], ["Final Chorus", "Everything at once", "All layers combined, ad-libs flying everywhere."]] },
  { name: "Prog Rock Epic", steps: [["Part I: Overture", "Instrumental", "Complex time signature introducing the musical themes."], ["Part II: The Call", "First vocals", "Abstract lyrics dealing with cosmic or philosophical themes."], ["Part III: The Journey", "Shifting sands", "Tempo changes, multiple different verses with no repeated chorus."], ["Part IV: The Battle", "Solo Section", "Dueling instruments, maximum complexity and tension."], ["Part V: Resolution", "Grand finale", "A massive, sweeping chorus that unites all previous themes."]] },
  { name: "The Slow Burn Arc", steps: [["Intro", "Silence & Space", "Barely there instrumentation, intimate hushed vocal."], ["Verse 1", "Whispered truths", "Short lines, lots of empty space between phrases."], ["Verse 2", "Layering", "Drums enter softly, vocals gain a bit of confidence."], ["Bridge", "The simmer", "Repeating a mantra as instruments slowly swell in volume."], ["The Climax", "Wall of Sound", "Screamed or belted vocals, explosive drums, overwhelming emotion."], ["Outro", "Sudden cut", "Instantly drops back to total silence or a single held note."]] },
  { name: "Neo-Soul Groove", steps: [["Intro", "Vibe Check", "Complex chord progression, spoken word intro."], ["Verse 1", "Conversational", "Laid back delivery, floating slightly behind the beat."], ["Chorus", "Harmonic bliss", "Thick vocal stacks, smooth and jazzy."], ["Verse 2", "Playful", "More ad-libs, interactive interplay between vocal and bassline."], ["Vamp / Outro", "The Jam", "Repeating the chorus progression while the vocalist improvises runs and scat-sings to fade."]] },
  { name: "The Two-Part Suite (Beat Switch)", steps: [["Part 1: Verse", "Aggressive", "Fast tempo, attacking the beat, confrontational lyrics."], ["Part 1: Hook", "Hype", "Short, sharp, repetitive."], ["The Switch", "Transition", "Record scratch, beat suddenly slows down and gets moody/ambient."], ["Part 2: Verse", "Introspective", "Slower flow, vulnerable lyrics, looking inward."], ["Part 2: Outro", "Spoken Word", "A philosophical or reflective spoken outro over fading chords."]] }
,
  { name: "The Cinematic Trailer", steps: [["Act I", "The Setup", "High tension, sparse instrumentation, whispered vocals."], ["Sudden Silence", "The Breath", "One second of total quiet before the drop."], ["Act II", "The Escalation", "Rhythmic pulses, growing orchestra, staccato vocals."], ["The Impact", "The Peak", "Massive low-end hit, single powerful screamed word."], ["Act III", "The Resolution", "Long fading synth pad, one final breathy line."]] },
  { name: "Indie-Folk Stomp", steps: [["Verse 1", "Solo Journey", "Acoustic guitar and vocal only. Story-heavy."], ["Chorus", "The Gathering", "Handclaps and foot stomps join in. Group harmonies."], ["Verse 2", "The Travel", "Mandolin or banjo joins. Dynamic builds."], ["Chorus", "Full Band", "Drums and bass enter for a celebratory feel."], ["Bridge", "The Campfire", "Everything drops back to a single rhythmic clap."], ["Final Chorus", "Uplifting Conclusion", "Full energy, ends on a long sustained acoustic chord."]] },
  { name: "Dark Techno Loop", steps: [["Intro", "Filter Sweep", "Muffled kick drum slowly becoming clearer."], ["Cycle 1", "The Foundation", "Repetitive vocal hook, heavy sub-bass rhythmic pulse."], ["Cycle 2", "The Addition", "Industrial percussion layers added every 8 bars."], ["Breakdown", "Synthesized Tension", "Drums stop, white noise risers build for 16 bars."], ["The Peak", "The Release", "Full energy, distorted vocal chops, maximum volume."], ["Outro", "The Fade", "Stripping layers away until only the kick remains."]] },
  { name: "The Power Ballad (80s Style)", steps: [["Verse 1", "Vulnerable Piano", "Soft, emotional vocal, setting a tragic scene."], ["Verse 2", "Synth Strings", "Bass enters, vocal becomes slightly more projected."], ["Chorus", "The Anthem", "Huge gated-reverb drums, soaring high-notes, massive hook."], ["Verse 3", "Guitar Texture", "Palm-muted electric guitars add a driving feel."], ["Chorus", "The Heartbreak", "Even more emotional delivery, added vocal ad-libs."], ["The Solo", "The Scream", "Screaming blues-rock guitar solo for 16 bars."], ["Final Chorus", "The Transformation", "Key change up a whole step. Maximum stadium energy."], ["Outro", "The Echo", "Final piano notes fade out into a long reverb."]] },
  { name: "Experimental Glitch-Pop", steps: [["Source", "Raw Idea", "Clean, dry vocal over a simple percussive click."], ["Processing", "The Artifact", "Vocal is processed through heavy bitcrushing and delay."], ["Chorus", "The Reconstruction", "Melody emerges through layers of synthetic glitching."], ["Deconstruction", "The Chaos", "Beat becomes erratic, switching time signatures."], ["Resolution", "The Signal", "Returns to a clean vocal for the final three words."]] },
  { name: "The Lullaby (Ambient)", steps: [["Part A", "The Descent", "Slow, descending melodic phrases. Whispered delivery."], ["Part B", "The Drift", "Vocals become wordless, weaving through soft pads."], ["Part C", "The Sleep", "Extreme reverb makes the voice sound like 100 people."], ["Ending", "Total Peace", "Sounds of waves or wind for the last 20 seconds."]] },
  { name: "Hard Rock Groove", steps: [["Intro", "The Riff", "Distorted guitar hook that defines the whole song."], ["Verse 1", "Steady Drive", "Bass and drums lock into a heavy, simple pocket."], ["Chorus", "The Shout", "Loud, unison vocals on a simple, punchy hook."], ["Verse 2", "The Push", "Guitar becomes more aggressive, adding fills."], ["Bridge", "The Grind", "Tempo slows down slightly, extremely heavy groove."], ["Final Chorus", "Max Volume", "All instruments at full power, heavy crash cymbals."], ["Outro", "Feedback Sink", "Ends on a feedback-drenched sustained power chord."]] },
  { name: "The Jazz Fusion Odyssey", steps: [["Theme", "The Head", "Complex unison melody between keys and vocal."], ["Variation 1", "The Expansion", "Melody is stretched and syncopated over 7/8 time."], ["Solo Section", "The Exploration", "Vocalist scat-sings a complex improvisational line."], ["Theme Reprise", "The Return", "Return to the original melody but with more energy."], ["Coda", "The Dissolve", "Song ends on a complex, unresolved jazz chord."]] },
  { name: "Gothic Doom Arc", steps: [["The Toll", "Introduction", "Sparse, heavy bass notes and a distant church bell."], ["Verse 1", "The Lament", "Extremely slow tempo, deep and mournful vocals."], ["Chorus", "The Weight", "Massive, sluggish drums and thick distorted guitar."], ["The Void", "Silence", "Everything stops for four hollow seconds."], ["Final Chorus", "The End", "Melodic funeral organ joins for a epic, dark finale."]] },
  { name: "The Tropical Summer Jam", steps: [["Intro", "Ocean Breeze", "Steel drums, wave sounds, and a relaxed 'yeah' ad-lib."], ["Verse 1", "The Sun", "Fast, rhythmic vocal delivery, bright and happy."], ["Chorus", "The Splash", "Explosion of brass and percussion, huge catchy hook."], ["Verse 2", "The Party", "More interactive ad-libs, energy levels stay high."], ["Bridge", "The Sunset", "Beat slows down, focus on a smooth melodic run."], ["Final Chorus", "The Night", "Add even more percussion layers for a big finish."]] },
  { name: "The Protest Anthem", steps: [["Verse 1", "The Problem", "Unaccompanied vocal, clear and powerful message."], ["Chorus", "The Call", "One simple instrument joins for a rhythmic backbone."], ["Verse 2", "The Stories", "More instruments join as the 'community' grows."], ["Chorus", "The Unity", "Multiple voices joining in for a massive chant."], ["Bridge", "The Demand", "High energy, aggressive delivery of the core goal."], ["Final Chorus", "The Movement", "Full band, stomps, claps, and group shouting."], ["Outro", "Resonance", "Ending on a single sustained group hum."]] },
  { name: "The Minimalist Loop", steps: [["Element 1", "The Seed", "A single four-note melodic phrase repeats forever."], ["Element 2", "The Pulse", "A simple kick drum enters on every beat."], ["Element 3", "The Human", "A spoken word poem is recited over the loop."], ["Element 4", "The Fade", "Each element is slowly removed until it's just silence."]] }
];

export const POVS = [
  "The Direct Confession (First Person: I/You)", 
  "The Storyteller (Third Person: He/She/They)", 
  "The Unreliable Narrator (Lying to the listener/themselves)", 
  "The Inner Monologue (Talking strictly to yourself)", 
  "The Ghost (Singing from beyond the relationship or life)", 
  "The Accuser (Second Person: Dictating exactly what they did)", 
  "The Fly on the Wall (Detached, clinical, emotionless observation)",
  "The Inanimate Object (Singing from the perspective of a place or thing)",
  "The Collective We (Singing on behalf of a generation or group)",
  "The Letter Writer (Addressing someone who will never hear it)",
  "The Future Self (Warning your younger self)",
  "The Bystander (Present for the tragedy, but powerless to stop it)",
  "The Manipulator (Gaslighting the listener with charm)",
  "The AI (A machine attempting to understand human emotion)",
  "The Interrogator (Asking relentless, unanswerable questions)"
];
export const DELIVERIES = [
  "Fast, triplet-heavy rhythmic flow with simple end rhymes",
  "Conversational, dragging slightly behind the beat with slant rhymes",
  "Long, sweeping, theatrical legato notes with vivid imagery",
  "Staccato, punchy, aggressive delivery with dense internal rhymes",
  "Slightly slurred, exhausted delivery with sparse rhymes",
  "Crisp, fast-paced enunciation with rhythmic wordplay",
  "Breathless and rushed, like running out of time, no-rhyme free verse",
  "Soulful, heavy melismatic runs with call-and-response phrasing",
  "Deadpan, spoken-word style with sharp modern phrasing",
  "Soft, breathy, close proximity delivery with internal echoes",
  "Chanted, monotonous, almost robotic recitation",
  "Wide, operatic vibrato with dramatic volume swells",
  "Scream-sung, tearing the vocal cords with raw emotion",
  "Mumbled, barely audible over the beat, forcing the listener to lean in",
  "Hyper-enunciated, musical theater-style projection",
  "A lazy, sung-spoken drawl dripping with sarcasm",
  "Frantic, overlapping vocal takes interrupting each other",
  "Pin-drop quiet whispering directly into the microphone",
  "Massive, gospel-choir supported belting",
  "Folk-style yodeling or sudden register flips into falsetto",
  "Aggressive, percussive grunts emphasizing the downbeat",
  "A smooth, buttery croon that never raises its volume",
  "Hysterical, crying delivery where the pitch frequently breaks",
  "Pitch-shifted down to sound like a demonic entity",
  "Sung entirely in a fragile, breaking head voice"
];
export const TWISTS = [
  "A sudden key change downwards in the final chorus",
  "The beat drops out completely for the most important lyrical reveal",
  "A completely unrelated genre takes over for the bridge",
  "The perspective shifts from the victim to the perpetrator halfway through",
  "Ending exactly as the song began, implying a repetitive cycle",
  "An extended, chaotic instrumental outro that contradicts the happy lyrics",
  "The song abruptly cuts off mid-sentence",
  "A hidden, acoustic version of the chorus plays after a long silence",
  "The narrator's voice slowly distorts until it becomes unrecognizable",
  "The tempo completely halves for the last 30 seconds",
  "A frantic, double-time rap finishes a slow ballad",
  "The chorus lyrics change entirely in the final repetition",
  "A massive orchestral swell that ends in a single, dry cough",
  "The intro plays backwards to end the track",
  "A bright, cheerful children's choir suddenly sings the darkest lyric",
  "The main instrument breaks or goes severely out of tune",
  "The vocal track deliberately glitches and stutters off-beat",
  "A 30-second field recording of rain interrupts the track",
  "The final chord resolves to a deeply unsettling dissonance",
  "The song loops perfectly so the end is identical to the beginning",
  "A spoken word monologue replaces the final chorus",
  "The beat switches to a waltz rhythm for the bridge only",
  "The lead vocal is suddenly replaced by a synthesized robot voice",
  "A massive, booming bass drop happens under a tiny, plucked acoustic guitar",
  "The key modulates up every single time the chorus hits"
];
export const EMOTIONS = ["Nostalgia", "Hope", "Resentment", "Longing", "Confidence", "Guilt", "Yearning", "Relief", "Regret", "Defiance", "Tenderness", "Jealousy", "Awe", "Grief", "Calm", "Restlessness", "Bittersweet", "Euphoria", "Paranoia", "Acceptance"];
export const PREMISES = [
  "A breakup song that sounds like a massive celebration",
  "A song about realizing you are the villain of the story",
  "A love song for a city you're leaving permanently",
  "A track about the terrifying freedom of failing entirely",
  "An upbeat dance anthem with devastatingly sad lyrics",
  "A slow, romantic ballad about someone you haven't met yet",
  "A confrontational track aimed directly at your past self",
  "A song about staying in a comfortable but dead relationship",
  "An ode to midnight drives to avoid going home",
  "A track detailing the specific grief of outgrowing your best friend",
  "A love song to the version of you that existed before the trauma",
  "A bitter anthem about watching the person who broke you succeed",
  "A song about the exact moment you realize you're turning into your parents",
  "A track romanticizing a toxic, co-dependent friendship",
  "An apology you know they'll never accept",
  "A narrative about finding your ex's old shirt and burning it",
  "A song capturing the electric anxiety of a first date in a new city",
  "A hymn for the burnouts who peaked in high school",
  "A chaotic track about making a spectacularly bad decision on purpose",
  "A love letter to the stranger who smiled at you on the subway",
  "A song about the paranoia that everything is going 'too well'",
  "An eerie track about moving into a house where someone died",
  "A song about pretending you don't care to win an argument",
  "A ballad for the specific loneliness of being surrounded by people",
  "A track about the awkwardness of running into an ex at the grocery store",
  "A defiant anthem about finally quitting a job you hate",
  "A song about the comforting numbness of depression",
  "A love song where the 'lover' is actually an addiction",
  "A narrative track about a heist gone wrong",
  "A song dedicated to the feeling of your phone dying when you're lost",
  "A track about the sheer exhaustion of having to 'be strong'",
  "An ode to the euphoria of canceling weekend plans to sleep",
  "A song about realizing your idol is actually a terrible person",
  "A track dealing with the imposter syndrome of sudden success",
  "A love song written from the perspective of a ghost haunting its widow",
  "A song about the exact moment you lose respect for someone",
  "An anthem about the terrifying realization that you are the adult in the room",
  "A track about trying to recreate a perfect memory and failing",
  "A song about the bittersweet relief of dropping a burdensome secret",
  "A narrative about a small-town scandal involving the mayor",
  "A love song to a fictional character you wish was real",
  "A track about the specific despair of a Sunday evening",
  "A song about falling out of love slowly, one papercut at a time",
  "An ode to the bizarre camaraderie of the smoking section",
  "A track about the jarring experience of waking up from anesthesia",
  "A song about forgiving someone who never even apologized",
  "A love song for the peace found at the bottom of the ocean",
  "An anthem for the aggressively mediocre and perfectly content",
  "A narrative about discovering a family secret hidden in the attic",
  "A song about the crushing finality of signing divorce papers"
];
export const EAR_CANDIES = [
  "A heavily distorted 808 bass slide",
  "A pitched-down, slowed vocal sample in the chorus",
  "A sweeping, cinematic cello solo in the bridge",
  "A hyper-compressed, punchy acoustic drum break",
  "A glitched-out, stuttering synthesizer lead",
  "A massive, gated-reverb 80s snare drum",
  "A lo-fi, crackling vinyl atmosphere underlying the whole track",
  "A sudden, completely dry vocal with all instruments dropping out",
  "A melodic, high-register walking bassline",
  "A shimmering, wide-panned acoustic guitar stereo track",
  "A heavily flanged drum fill leading into the hook",
  "A reverse cymbal crash leading into the first verse",
  "A vocal ad-lib run through a megaphone effect",
  "A syncopated cowbell pattern buried deep in the mix",
  "A massive, room-shaking sub-bass drop on the first beat of the chorus",
  "A cascading, arpeggiated harp glissando",
  "A layer of crowd noise or cheering underneath the solo",
  "A heavily autotuned harmony panned hard left and right",
  "A sudden, stark silence before the final chord",
  "A detuned, wobbly tape-stop effect on the master track",
  "A subtle, rhythmic breathing loop acting as percussion",
  "A screeching, feedback-drenched guitar harmonic",
  "A delicate music box melody tinkling in the background",
  "A panning laser synth zapping from ear to ear",
  "A heavy, metallic anvil strike used as a snare drum",
  "A choir of synthesized monks chanting a long drone",
  "A rapidly auto-panned shaker that makes you dizzy",
  "A heavily sidechained, swelling white noise riser",
  "A vocal chop melody that sounds like seagulls crying",
  "A deep, rumbling cinematic impact boom",
  "A frantic, unquantized jazzy snare fill",
  "A delicate acoustic squeak from fingers sliding on guitar strings",
  "A layer of distorted police sirens in the background",
  "A bubbly, formant-shifted alien vocal layer",
  "A bitcrushed, 8-bit explosion sound effect",
  "A perfectly clean, jazzy ride cymbal playing swing time",
  "A monstrous, roaring vocoder chord progression",
  "A subtle, rhythmic clicking of a pen or lighter",
  "A massive, cavernous church bell tolling on the downbeat",
  "A fluttering, tremolo-picked mandolin adding texture"
];
export const ENERGY_CONTOURS = [
  "A slow burn that explodes only in the final chorus",
  "Relentless, driving energy from start to finish",
  "Starts massive, drops to a whisper, ends in chaotic noise",
  "A steady, hypnotic groove that slowly adds layers",
  "Quiet verses with sudden, jarringly loud choruses",
  "Rolling waves of intensity that build and recede cyclically",
  "High energy up until a stark, stripped-back bare acoustic bridge",
  "A constantly accelerating tempo that reaches a frantic peak",
  "A flat, stoic, unchanging groove that relies on lyrical tension",
  "A chaotic, unpredictable structure jumping between loud and soft",
  "A rapid, breathless sprint that collapses into a slow halftime outro",
  "Starts acoustic and intimate, gradually becoming a full stadium rock anthem",
  "A massive wall of sound that slowly peels away instruments until only a vocal remains",
  "Two slow, moody verses leading to an absolutely unhinged, double-time dance break",
  "A false ending of total silence followed by a blistering guitar solo",
  "Consistently medium energy, feeling like a comfortable, easy drive",
  "A frantic, jarring intro that settles into a smooth R&B groove",
  "Starts with a massive drop, then spends the rest of the song trying to rebuild that energy",
  "An eerie, tension-filled build that never actually drops, leaving the listener unresolved",
  "A bouncy, playful energy that suddenly turns intensely dark and heavy in the bridge"
];
export const VOCAL_ARCHETYPES = [
  { name: "The Confessor", verse: "close-mic, intimate, restrained", chorus: "open tone, warm lift", bridge: "nearly spoken, vulnerable" },
  { name: "The Rebel", verse: "gritty, forward, rhythmic phrasing", chorus: "bigger edge, punch consonants", bridge: "half-sung grit, tension" },
  { name: "The Dreamer", verse: "airy, soft, floating vowels", chorus: "soaring, layered harmonies", bridge: "breathy clarity, emotional crack" },
  { name: "The Villain", verse: "low and controlled, theatrical", chorus: "dramatic lift, sharp dynamics", bridge: "cold whisper → sudden snap" },
  { name: "The Storyteller", verse: "clear articulation, narrative drive", chorus: "anthemic, singalong", bridge: "pause-heavy, honest delivery" },
  { name: "The Diva", verse: "soulful runs, confident tone", chorus: "massive belting, extreme vibrato", bridge: "high-register acrobatic melisma" },
  { name: "The Ghost", verse: "fragile head voice, distant", chorus: "reverb-drenched, ethereal choir", bridge: "wordless, haunting wailing" },
  { name: "The Robot", verse: "flat pitch, hyper-quantized", chorus: "thick vocoder chords, synthetic", bridge: "glitching, stuttering robotic syllables" },
  { name: "The Punk", verse: "sneering, out-of-breath fast", chorus: "shouted gang vocals", bridge: "raw, throat-shredding scream" },
  { name: "The Lounge Singer", verse: "buttery smooth, behind the beat", chorus: "classic crooning, wide vibrato", bridge: "playful scatting and ad-libs" }
];

export const INST = [
  "Fuzzy analog synths, tight 808s, and a heavily distorted vocal sample",
  "Nylon string acoustic, brush drums, and a sweeping cello",
  "Washed-out shoegaze guitars, driving bass, and buried vocals",
  "Crisp piano, soaring strings, and a massive sub-bass",
  "Lo-fi drum break, jazzy Rhodes piano, and vinyl crackle",
  "Down-tuned 8-string guitars, blast beats, and a guttural synth line",
  "Upright bass, muted trumpet, and soft finger-snaps",
  "Massive supersaw synths, four-on-the-floor kick, and sidechained pads",
  "Clean Stratocaster, groovy bassline, and tight funk drums",
  "Mellotron flutes, 12-string acoustic, and tambourine",
  "Gritty distorted bass, trap hi-hats, and eerie music-box bells",
  "Reverb-drenched slide guitar, slow heavy kick, and distant vocal hums",
  "8-bit chiptune leads, glitchy percussion, and a vocoder",
  "Fuzzy bass, garage rock drums, and gang vocals",
  "Lush orchestral harp, glockenspiel, and deep timpani rolls",
  "Clattering metallic percussion, droning synths, and aggressive whispers",
  "A grand piano run through a cassette tape simulator, accompanied by vinyl hiss",
  "Plucky pizzicato strings, a bouncing tuba bassline, and marching snares",
  "Heavily autotuned, wordless vocal chops serving as the lead melody",
  "A dusty, chopped-up soul sample layered over boom-bap drums",
  "A frantic, constantly shifting arpeggiator over a relentless techno beat",
  "Tremolo-picked surf guitar, a bouncy bassline, and splashy ride cymbals",
  "A solitary electric guitar plugged into a cranked tube amp, crying out with feedback",
  "Dense layers of acappella harmonies beatboxing a complex rhythm",
  "A massive, detuned brass section over halftime UK Drill drums",
  "Ethereal choir pads, subtle chimes, and a deep, breathing sub-bass",
  "Frantic bongos, a driving Latin piano montuno, and a horn section",
  "A twangy baritone guitar, slow marching drums, and lonely whistling",
  "Stabbing orchestra hits, rapid-fire hi-hats, and a bouncy 808",
  "A solitary kalimba playing a haunting melody over rain sounds",
  "Distorted drum machines, shrieking industrial synths, and shouted vocals",
  "A breezy bossa nova guitar, light shaker, and a breathy flute",
  "Grinding, acidic TB-303 baselines and punchy 909 drums",
  "A sweeping, cinematic French horn section over rolling toms",
  "A bright, plucky mandolin over a stomping, acoustic folk beat",
  "Glitchy, micro-edited percussion loops and deep FM synthesized bass",
  "A slow, wailing saxophone solo echoing through a massive reverb chamber",
  "Tight, muted rhythm guitar playing intricate 16th-note funk patterns",
  "A booming taiko drum ensemble and atmospheric Japanese koto",
  "A wobbly, pitch-drifting electric piano over a lazy reggae riddim",
  "A razor-sharp dubstep wobble bass trading phrases with a laser synth",
  "A lonely accordion playing a melancholic waltz in a minor key",
  "A choir of artificial intelligences singing in perfect, unnerving harmony",
  "Brutal, palm-muted chugs and rapid-fire double kick drums",
  "A warm, glowing Hammond B3 organ with heavy Leslie speaker vibrato",
  "A single, massive 808 kick drum hitting every four bars, no other hats or snares",
  "Sparkly, dreamy DX7 electric piano and a driving, chorus-drenched bass guitar",
  "A relentless driving krautrock drumbeat under a droning, single-note synth",
  "A cheerful ukulele, handclaps, and an upright bass",
  "A massive choir chanting in Latin over a doom metal riff"
];
export const FORBIDDEN = ["Love, Heart, Baby, Cry, Tonight", "Girl, Boy, World, Fire, Desire", "Yeah, Oh, Stop, Go, Time", "Tears, Years, Fears, Eyes, Lies", "Walk, Talk, Sleep, Weep, Deep", "Sun, Moon, Stars, Sky, Fly", "Forever, Never, Always, Please, Down", "Crazy, Hazy, Night, Light, Right", "Sad, Mad, Glad, Bad, Good", "Alone, Home, Phone, Stone, Bone"];
export const TITLE_ADJ = ["Neon", "Hollow", "Midnight", "Static", "Velvet", "Fading", "Golden", "Broken", "Silent", "Bitter", "Savage", "Crimson", "Electric", "Restless", "Suburban", "Plastic", "Ghostly", "Tangled", "Heavy"];
export const TITLE_NOUNS = ["Regret", "Echoes", "Bones", "Shadows", "Wires", "Hearts", "Ghosts", "Whispers", "Sunsets", "Tears", "Strangers", "Skies", "Mirrors", "Nights", "Lies", "Promises", "Cigarettes", "Memories"];
